version: "3.9"
services:
  app:
    container_name: next_quanaocongnhan
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/:/app/data/
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://user:password@postgres_quanaocongnhan:5432/db?schema=public
    env_file:
      - .env.local
    links:
      - postgres
    networks:
      - internal-domain
    depends_on:
      - postgres
  postgres:
    container_name: postgres_quanaocongnhan
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal-domain
  pgAdmin:
    container_name: pgadmin_quanaocongnhan
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quanaocongnhan.com
      PGADMIN_DEFAULT_PASSWORD: 258456C@p
    ports:
      - "5555:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - internal-domain
networks:
  internal-domain:
    driver: bridge