version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
      
    volumes:
      - ./_images:/app/_image
      - ./_posts:/app/_posts
      - ./data.json:/app/data.json
