version: '3'
services:
  app:
    container_name: nextjs_quanaocongnhan
    image: chauanphu/e-quanaocongnhan-app:1.0.3
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true