version: '3'
services:
  app:
    container_name: nextjs_quanocongnhan
    image: chauanphu/e-quanaocongnhan-app:1.1.4
    environment:
      - NEXTAUTH_URL=https://quanaocongnhan.com
      - DATABASE_URL=postgresql://user:password@postgres_quanaocongnhan:5432/db?schema=public
    env_file:
      - .env.local
    volumes:
      - ./data/:/app/data/
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - nginx-network
      - internal-domain
  postgres:
    container_name: postgres_quanaocongnhan
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal-domain
  pgAdmin:
    container_name: pgadmin_quanaocongnhan
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@quanaocongnhan.com
      PGADMIN_DEFAULT_PASSWORD: 258456C@p
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nginx-network
      - internal-domain
networks:
  nginx-network:
    external: true
  internal-domain:
    driver: bridge
volumes:
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data 