version: "3.9"
services:
  next:
    container_name: next_quanaocongnhan
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/:/app/data/
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.local
    links:
      - postgres
    networks:
      - internal-domain
    depends_on:
      - postgres
  postgres:
    container_name: postgres_quanaocongnhan
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - internal-domain

networks:
  internal-domain:
    driver: bridge