version: '3'
services:
  app:
    container_name: nextjs_quanocongnhan
    image: chauanphu/e-quanaocongnhan-app:1.0.3
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - nginx-network
  db:
    image: postgres
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  nginx-network:
    external: true
volumes:
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webdata 