
version: '3'
services:
  mongodb:
    container_name: db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env.local

volumes:
  mongodb_data:
